# source verilog files
SYNTH_SOURCES=lc4_regfile.v register.v mux_decoder.v
TOP_SYNTH_MODULE=lc4_regfile

# testbench files
#TESTBENCH=testbench_lc4_regfile.v
TESTBENCH=testbench_lc4_decoderMux.v
TOP_TESTBENCH_MODULE=test_regfile

include ../common/make/vivado.mk
